name: justdrink
description: "water tracker"

version: 1.0.3

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider:
  hive: ^2.2.3
  hive_flutter: ^1.0.0
  hive_generator: ^2.0.1
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  intl: ^0.20.2
  awesome_notifications: ^0.10.1
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf

